default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: staffcraft_rails_development
  username: <%= ENV['USER'] %>  # Usa tu usuario de Mac automáticamente
  password:
  host: localhost

test:
  <<: *default
  database: staffcraft_rails_test
  username: <%= ENV['USER'] %>
  password:
  host: localhost

production:
  <<: *default
  database: staffcraft_rails_production
  username: staffcraft_rails
  password: <%= ENV["STAFFCRAFT_RAILS_DATABASE_PASSWORD"] %>
